### ISSUE TITLE
Naming standard for feeders, tasks, workflows

### ISSUE THREAD

**Issue by stark525** [cirrus-geo/cirrus-geo#124]
Right now, it seems the core components have a preference (based on how they are generated by the templates):

**workflows**: spear-case-naming
**tasks**: PascalCase (because they are Cloudformation resource names
**feeders**: I'm not sure yet

It would be good to at a minimum document what the preference is. Ideally, the template could validate as well, to ensure you're not creating CF resources that are invalid.

**Comment by jkeifer** [comment]
OBE with v1
