### ISSUE TITLE
Handle unset subnet envs gracefully

### ISSUE THREAD

**Issue by sjwoodr** [cirrus-geo/cirrus-geo#125]
The cirrus.yml file has subnets defined as: 
```     Subnets:
       - ${env:SUBNET_1}
       - ${env:SUBNET_2}
       - ${env:SUBNET_3}
       - ${env:SUBNET_4}
```

When running `cirrus build` the env variables are used to inject the subnets into the generated serverless.yml file.

If one or more of the subnet env vars are undefined, the resulting serverless.yml file has them set to `null` which fails cloudformation template validation.  A better solution would be for the `cirrus build` step to evaluate the environment variables and if they are unset, remove the array entry from the generated Subnets array rather than adding a `null` entry. 

For now the workaround is to remove the un-needed subnets from cirrus.yml file and that is fine, but it would be more fault tolerant if it would handle the case of an unset SUBNET_x variable.

**Comment by jkeifer** [comment]
This was resolved with the default `cirrus.yml` changes that went into the 0.7.0 release. In essence, we default the file to reference a basic VPC config as provided by a generated cloudformation template. If the user wants to modify that config to change the subnets, or wants to use an external VPC, it is on them to make those changes accordingly.

In short, the default file handles an unset subnet var gracefully by not relying on them in the first place.
