### ISSUE TITLE
Rename `output_options` param dictionary to `asset_upload_options`

### ISSUE THREAD

**Issue by matthewhanson** [cirrus-geo/cirrus-geo#128]
The `output_options` field in the `process` definition has caused some confusion. Improved docs will help of course, but it's a rather ambiguous name.  It can be more explicit, these are the options that are passed to the [upload_item_assets](https://github.com/cirrus-geo/cirrus-lib/blob/main/src/cirrus/lib/transfer.py#L126) function in cirrus-lib, so a better name would be `asset_upload_options` or even just `upload_options`.

The process lambda can check, update the key, and print a deprecation warning.

**Comment by jkeifer** [comment]
Should the payload be "upgraded" to use the new version? Probably, in case you need to rerun a saved payload in the future and the old support has been removed.

`upload_options` is the preferred name here.
