### ISSUE TITLE
Add migrations

### ISSUE THREAD

**Issue by matthewhanson** [cirrus-geo/cirrus-geo#13]
Figure out how to perform migrations between 0.2 and upcoming 0.4 (note there is no cirrus 0.3 planned, as it's being bumped to match minor versions with cirrus-lib).

**Comment by jkeifer** [comment]
@matthewhanson Is this still applicable?

**Comment by matthewhanson** [comment]
No, we may need to add migrations later if we update schema, but this is OBE
