### ISSUE TITLE
Provide list of valid workflows per collection in API

### ISSUE THREAD

**Issue by matthewhanson** [cirrus-geo/cirrus-geo#14]
Getting stats per input_collections is fine if there's only one workflow per set of input collections. But if there are multiple workflows stats should be based from each combination of input_collections and workflow.

Thus:

```
/collections/<input_collections>
```
should be more like
```
/collections/<input_collections/workflow
```

**Comment by jkeifer** [comment]
Essentially a duplicate of #133.
