### ISSUE TITLE
stac-api feeder as a workflow

### ISSUE THREAD

**Issue by matthewhanson** [cirrus-geo/cirrus-geo#159]
Random thoughts on turning the stac-api feeder in Cirrus into a Workflow

# Input payload

This input payload contains no STAC Items, only task parameters. The STAC API Crawl 
task will use the provided query to fetch all matching STAC Items from the API
and then publish each of the resulting Items as a single feature FeatureCollection
with the given process deinition attached.

Here is an example input payload. Note that the `stac-api-crawl` task contains a 
`process` definition that will be used for the processing of all found Items.

```json
{
    "id": "usgs-landsat/workflow-stac-api-crawl",
    "type": "FeatureCollection",
    "features": [],
    "process": {
        "workflow": "stac-api-crawl",
        "input_collections": ["usgs-landsat"],
        "tasks": {
            "stac-api-crawl": {
                "url": "https://landsatlook.usgs.gov/stac-server",
                "search": {
                    "intersects": "<geometry>",
                    "datetime": "2021"
                },
                "process": {
                    "workflow": "process-landsat",
                    "upload_options": {
                        "path_template": "s3://<my-bucket>/${collection}/${id}",
                        "public_assets": "ALL"
                    },
                    "tasks": {
                        "preprocess-landsat": {
                            "param1": "val1"
                        }
                    }
                }
            }
        }
    }
}
```

Each found STAC Item will be published as a Cirrus Process payload back to Cirrus.

There is typically no `publish` step in this workflow, unless it is desired to mirror the contents
of the STAC API to the local STAC API.

**For each item found construct the Process payload and publish to the SNS topic.** Assuming a given
STAC Item is fetched from the API there should be no possibility of error here.

Some questions:
    - The ID should be the hash of the payload ?
    - If an error happens during paging through the API, what happens?

Example output Process Payload

```json
{
    "id": "usgs-landsat/workflow-stac-api-crawl",
    "type": "FeatureCollection",
    "features": [
        "<LandsatStacItem>"
    ],
    "process": {
        "workflow": "process-landsat",
        "upload_options": {
            "path_template": "s3://<my-bucket>/${collection}/${id}",
            "public_assets": "ALL"
        },
        "tasks": {
            "preprocess-landsat": {
                "param1": "val1"
            }
        }
    }
}
```

This doesn't completely remove the need for a "feeder"...something still needs to create the
original input payload(s) which, for a large number of items, should parition the API into
sets of query parameters.  e.g., a payload for 2015, 2016, etc.

**Comment by jkeifer** [comment]
@matthewhanson Do you need anything more for this on the cirrus-geo side? That is, can this issue be closed, or do we need to track further action items?

**Comment by matthewhanson** [comment]
Nope, we can close this.  Implemented this as a workflow, which works like any other task except it queues payloads.  We may want to consider a generic class built on stac-task (or, more likely, a base class that gets factored out) that promotes this.
