### ISSUE TITLE
`ProcessPayload.get_payload()` size limit is too low

### ISSUE THREAD

**Issue by jkeifer** [cirrus-geo/cirrus-geo#191]
Looks like it is currently 30KB, but SQS and step functions both support 256KB messages/payloads.

**Comment by jkeifer** [comment]
@matthewhanson Might you have any context on why the low limit here?

**Comment by ircwaves** [comment]
Offline discussion with @matthewhanson results in agreement that bumping this limit up makes sense.

And, reviewing code shows this has made its way into both `release/v0` and `main` with a limit of 250KB.
