### ISSUE TITLE
`rerun` feeder should be able to re-run payloads with a terminal state

### ISSUE THREAD

**Issue by jkeifer** [cirrus-geo/cirrus-geo#199]
Payloads in the `COMPLETED` and `INVALID` states cannot be re-run by the current implementation of the `rerun` feeder if they did not already have the `"replace": true` key in their process definition, as it has no facility for setting that key for the re-run payload. This is because it currently just resolves the payload url and sends that along to process to resolve from S3.

Two options for fixing this oversight:
* Resolve the payloads from S3 in `rerun`, apply the `replace` key, then send the message to `process`
* Allow `process` to use a `replace` key in the url payload to set that on the resolved payload

The former requires more logic in `rerun` that effectively duplicates operations already supported in `process`, and for large payloads would require pulling them down, modifying them, pushing them back up to S3, then pulling them down again in `process`.

The latter adds additional logic to process to understand a sort of ad hoc and perhaps not well-considered interface for replacements, and seems a slippery slope to having `process` support for modifying payloads in other ways. We just pulled such features out of `process` to keep its logic simple.

**Comment by matthewhanson** [comment]
Actually, looks like the StateDB.process [already takes a `process` keyword](https://github.com/cirrus-geo/cirrus-geo/blob/main/src/cirrus/lib2/process_payload.py#L354).  But the rerun feeder can't use right now since it just adds things to the queue and isn't calling process directly.  I think this is what you were getting at with using `replace` in the url payload?   

So in the case of a URL payload, you'd add replace here:

```
{
   "url": "s3://yada/yada/yada"
   "replace": true
}
```

So then the process Lambda would set the replace keyword of `ProcessPayloads.process` to true if it were included in the payload.  In the case where the payload does not have a "url" field, it would use the normal replace in the `process` definition?

**Comment by jkeifer** [comment]
Yes.

I'd propose changing `ProcessPayload` instantiation to pop `ProcessPayload.process.replace` and set a new property `ProcessPayload.replace` to the popped value. Instantiating a `ProcessPayload` should also take a new parameter `replace`, which can take the value of `replace` from the top-level payload in the case of URL payloads.

Popping `replace` from `ProcessPayload.process` will mitigate the concern about payloads being persisted to S3 with `replace` set. Of course, due to the way we have `ProcessPayload` be it's own dict, `ProcessPayload.replace` would be persisted to S3. This is not ideal, but also not the end of the world as it won't be used to trigger replacement.

That said, a likely better solution here is to compose the payload into `ProcessPayload` using one of these solutions:

* define well-known top-level keys for those properties to be persisted to S3 (I did something like this in the `cirrus-mgmt` plugin to extract persisted properties into a parent data class, which had the json-conversion methods on it using `dataclasses.asdict(self)`)
* put the entire payload data structure under a single key, say as `payload` or `raw`

I'd hazard to say while the latter might be a more inconvenient refactor, it would probably be the best long-term solution, and would eliminate some weirdness we already have, e.g., `ProcessPayload.process` vs `ProcessPayload["process"]`.

**Comment by jkeifer** [comment]
I'm closing this ticket as OBE as rerun has been removed from v1 and no one has actually complained of any production impacts from this issue. If the latter point changes and we need to revisit a solution for a v0 deployment suffering negative impacts from this problem we can reopen this issue.
