### ISSUE TITLE
Identify boilerplate handler code and recommendations in docs

### ISSUE THREAD

**Issue by stark525** [cirrus-geo/cirrus-geo#23]
There are some fantastic features that are part of task handlers that could use additional documentation:
- Boilerplate code that every handler should have
- Working with the catalog payload object
- The preferred way to handle logging and exceptions
- Examples for adding to the STAC record before publishing
- The CLI, why it's important, and how it can be used for local development
- Test payloads / testing business logic in the handler

**Comment by jkeifer** [comment]
This is solved by stac-task (https://github.com/stac-utils/stac-task).
