### ISSUE TITLE
Data migration between STAC catalogs and/or collections

### ISSUE THREAD

**Issue by tvance34** [cirrus-geo/cirrus-geo#24]
Provide an automated mechanism for users to copy data between different STAC catalogs.  

Use Case:
I'm a user with multiple environments, each using a different instance of STAC API.  The data in one environment may become stale/bad/limited/etc at one point, and I'd like to copy new/better/updated data from one of my other STAC instances so that I have quality data in all of my catalogs.

**Comment by stark525** [comment]
I think the ultimate solution is at least one utility script (not sure if in here, cirrus-lib, or a new project) I'd like to be able to:

`./cirrus-migrate.py [--create-if-not-existing=True] --source-catalog <path-to-stac-server-1-catalog> --dest-catalog <path-to-stac-server-2-catalog>`

Under the covers it would:
- Move the image data in underlying S3 buckets
- Move the STAC data between elasticsearch indexes, updating paths via cirrus-lib, presumably
- Make necessary changes in state DBs in source and destination (if multiple environment/account)
