### ISSUE TITLE
s3transfer slimPatterns version conflict

### ISSUE THREAD

**Issue by pjhartzell** [cirrus-geo/cirrus-geo#242]
With cirrus-geo 0.10.0 installed, seeing `[ERROR] ImportError: cannot import name 'is_s3express_bucket' from 'botocore.utils' (/var/runtime/botocore/utils.py)`.

Need to add

      - "s3transfer/**"
      - "s3transfer-*/**"

to the default `slimPatterns` or otherwise modify the default `slimPatterns`.

**Comment by jkeifer** [comment]
So if running v0 make sure _not_ to slim boto to prevent this problem. But this is OBE with v1.
