### ISSUE TITLE
separate dependencies packaged with lambda and those needed for CLI

### ISSUE THREAD

**Issue by philvarner** [cirrus-geo/cirrus-geo#255]
As of 0.12.0, all of the requirements for cirrus-geo get installed in the lambdas. Some of these are unnecessary, e.g., click and cfn-flip. It would be better to have the requirements broken out in to a minimal set for install_requires and an extra_requires={"cli": [ click, etc ...]}.

**Comment by jkeifer** [comment]
OBE with v1
