### ISSUE TITLE
Retry mechanism for Memory failures

### ISSUE THREAD

**Issue by tvance34** [cirrus-geo/cirrus-geo#26]
If a job fails at the specified memory configuration, provide a retry logic that would process the job at a new/higher memory setting, and increment again if its fails until it ultimately succeeds.

**Comment by jkeifer** [comment]
How you accomplish this is highly dependent on the input data and can be done by inspecting the input payload within a workflow and deriving dynamic resource requirements. As such there are no framework-related changes we can make in cirrus to support this generically.
