### ISSUE TITLE
Build API to use state db and return cost breakdown

### ISSUE THREAD

**Issue by stark525** [cirrus-geo/cirrus-geo#27]
Related to #25 , and extending it a bit further.

It would be helpful to know how how many failed jobs have occurred, and how much $ that has cost me. Or what the breakdown my AWS bill is from only cirrus.

Thinking like the AWS billing console, but for only cirrus resources and workflows.
Compute Total: $1000
Success: $800
Failed: $200

Since this is in the statedb, if we knew how much one item roughly cost (#25), we could generate this type of report.

**Comment by jkeifer** [comment]
Cost estimation is still a pain point. It would be great if we had the ability to inspect costs via the FilmDrop UI but at this time work related to costing is not planned.

We will revisit this in the future when we have a better story around the costs and how to track them in a meaningful and useful way.
