### ISSUE TITLE
Mapping/translation from various input to search

### ISSUE THREAD

**Issue by rudnyg** [cirrus-geo/cirrus-geo#29]
Want to be able to process various input files and do a remapping based on input. 

#### 1) Determine naming convention needed to ingest a particular file format (json, csv, xml, parquet, etc)
**field name:** lat  **Description:** Longitude field function will look for and extract
**field name:** long  **Description:** Longitude field function will look for and extract

Using this method requires some pre-process work to make sure that file is in format needed. 

#### 2) Be able to do on the fly translations/mapping 
Based on workflow can have values and descriptions defined for the `task_values` and the same for `mappings`

#### Lets say our task has these defaults values needed to operate: 
`date`: "Date of measurement"
`longitude`: "Longitude of measurement "
`latitude`: "Latitude of measurement" 

#### The values in file: 
`sample_date`: "Date of measurement"
`lon`: "Longitude of measurement "
`lat`: "Latitude of measurement" 

For example: 
```json 
  "url": "https://earth-search.aws.element84.com/v0",
  "search": {
    "collections": [ "collection"]
  },
  "process": {
    "workflow": "my-workflow"
    },
    "tasks": {}
  },
  "task_values": {
    "file_name": "my_file.csv",
   "Important_field": "value"
  },
 "mappings":  {
   "date": {
     "value": "sample_date",
     "format": "iso"
 },
   "longitude: {
     "value": "lon"
 },
   "latitude": {
     "value": "lat"
 }
}
}
```
In this example you have the field you want to remap and the value that should be used. 
This is an example that can be used but can be improved upon.

**Comment by jkeifer** [comment]
This seems like it belongs at a layer above cirrus, such as a custom feeder or equivalent. Closing as not planned.
