### ISSUE TITLE
Add new dynamic workflow with optional tasks

### ISSUE THREAD

**Issue by matthewhanson** [cirrus-geo/cirrus-geo#3]
Now that the `isPresent` and `isNull` fields in Choice Rules are part of the AWS Step Language spec, a workflow can be created that replaces publish, mirror, and cog-archive with a single workflow. See here: https://github.com/awslabs/statelint/issues/7

By using the `isNull` and/or `isPresent` fields Choice states can be added to a workflow to only execute certain tasks if the field is present.

Thus, if a process block looked like:
```
{
    ....
    "workflow": "cirrus",
    "tasks": {
        "publish": {}
    }
}
```
then the workflow would not execute the `copy-assets` or `convert-to-cog` tasks.  As opposed to now, which is that each task will be run even if it does nothing.

Workflows would need to be updated to include a field for each task to be run, even if it has no parameters (as shown in example above)

**Comment by jkeifer** [comment]
We have since determined that single-purpose workflows are a cirrus best practice and we have also removed all built-in workflows in v1. Closing as OBE.
