### ISSUE TITLE
Full event tracing and observability enhancements. 

### ISSUE THREAD

**Issue by rudnyg** [cirrus-geo/cirrus-geo#30]
- Currently most workflows involve an event passing from feeder -> to a queue -> maybe another lambda/batch task -> step functions -> final destination. 
- There is no easy way of figuring how long an event took to go from start to completion.
- There is no east way to figure out if an event failed without searching thru individual logs for aws services. 
- Need a way to be able to get an event id and see the steps it took and time it took to run to completion or failure.

**Comment by jkeifer** [comment]
Between the event database and the workflow event topic we have the primitives to address this issue, as well as the comprehensive step function logging that is available. However, we don't have a good story around how to use these better beyond wanting to make such information available within the FilmDrop UI.

We will revisit this in the future when we have a better story around the desired experience and can plan the work required. Closing as not planned for now.
