### ISSUE TITLE
Update to use PySTAC

### ISSUE THREAD

**Issue by matthewhanson** [cirrus-geo/cirrus-geo#34]
Currently messages are treated simply as dictionaries, with no STAC library (it had earlier used sat-stac before switching to straight JSON).

cirrus-lib should accept PySTAC entities where appropriate, and the core Lambdas at least should use PySTAC which will help with validation and make other things possible in the future, like maintaining a static STAC catalog.

**Comment by matthewhanson** [comment]
Most of Cirrus uses straight dictionaries of STAC Items. This is limiting in that we aren't taking advantage of the validation and convenience features of PySTAC. However, it may be that using dictionaries is faster, and sufficient.

Review code in cirrus and in cirrus-lib to identify where using PySTAC vs dictionaries may be a benefit.

**Comment by jkeifer** [comment]
@matthewhanson Is this still issue still applicable?

**Comment by matthewhanson** [comment]
No, stac-task uses PySTAC, and you get input items as PySTAC Items or as dictionaries
