### ISSUE TITLE
Add PUBLISHED status and SNS topic to set

### ISSUE THREAD

**Issue by matthewhanson** [cirrus-geo/cirrus-geo#35]
Cirrus statuses include PROCESSING, COMPLETED, FAILED, and INVALID.

COMPLETED indicates job is done and the output Items were published to an SNS topic, but does not indicate it was actually added to an index and is available in an API.

Recommend adding PUBLISHED status indicating it is in the index. An SNS topic and Lambda would need to be added so the the STAC API (stac-server) could publish to it and it would be marked appropriately in the database.

**Comment by jkeifer** [comment]
Not sure if this is still something that is desired, but I clicked on this and have a response:

A workflow may produce multiple output items. As such, the payload status can't effectively represent PUBLISHED unless you can track a status per output item then aggregate to the payload itself. For example, if the outputs array tracked output item and status then you could update each one as they are PUBLISHED, only updating the payload status to PUBLISHED once all of the output items have been PUBLISHED.

But how do you find the payload record based on an output item? That seems like a difficult problem with our current dynamo schema. If we were using a relational database then this could be a lot easier, but perhaps still of questionable value.

At a certain point we start effectively implementing a stac-api index within the state database. This leads me to think that PUBLISHED is really not a cirrus state at all, unless the cirrus state db is itself the stac-api index, but then is PUBLISHED even a state we care about?

Moreover, we 1) have a race condition with `update-state`, as they are both event based and non-deterministically ordered, and 2) `publish` is not necessary the terminal task in a workflow, nor it is always run only once. Perhaps this doesn't matter too terribly much if we simply use all output items having a PUBLISHED state combined with the workflow being in a COMPLETED state.

But still it seems to be conflating item states with execution states (which are already conflated with the payload's state). So I'd argue that this PUBLISHED state really only makes sense for the output items themselves.

Just some random thoughts.

**Comment by matthewhanson** [comment]
I agree, in the current statedb it does not make sense to have a PUBLISHED state. I'm not even sure what use it is, since some workflows may not even publish items, such as the queuing workflows I've been using for earth-search, which only queue new payloads to Cirrus.

What is needed is a way to track any items that should have been published but weren't.  This is currently handled by a DLQ on the stac-api side, but since nothing in the DLQ is subsequently processed they could eventually time out.   I'd like to have some tools to perform reconciliation between the statedb and the published items to find any discrepancies.
