### ISSUE TITLE
Add a proj/geometry task for generating proj info, updating footprint

### ISSUE THREAD

**Issue by matthewhanson** [cirrus-geo/cirrus-geo#36]
Add a task to populate fields in the [projection extension](https://github.com/stac-extensions/projection) - specifically, proj:epsg, proj:shape, proj:transform and proj:centroid. Additional fields providing the projection in native coordinates are not as useful.

This task would use rasterio to pull out these values from the file, which means it has to be downloaded or accessed remotely. Remote access should be much faster as it's just pulling header info. Check both.

As part of this task, or perhaps another task (?) add an option for regenerating the data footprint, see this issue:
https://github.com/stac-utils/stactools/issues/85

**Comment by jkeifer** [comment]
This is OBE because we are no longer adding built-in tasks.
