### ISSUE TITLE
Add JSON schema for feeders, tasks and workflows

### ISSUE THREAD

**Issue by matthewhanson** [cirrus-geo/cirrus-geo#4]
Each feeder needs a JSON schema for payload parameters

Each task should contain a JSON schema of parameters for the task (process->tasks->taskname)

Each workflow should have a JSON schema indicating process parameters and should combine STAC schema along with the schema from any task that is part of the workflow.

**Comment by jkeifer** [comment]
This concern should be addressed in stac-task. We already know that pydantic is likely the reight strategy for expressing payload requirements and generating jsonschemas.
