### ISSUE TITLE
malformed search queries may return all items in a collection and try to process 

### ISSUE THREAD

**Issue by stark525** [cirrus-geo/cirrus-geo#48]
If a search query is malformed, e.g. it contains the wrong field name or type, it will silently ignore the search filters and return all items in the collection.

This is using the feed-stac-api.

This can have disastrous consequences as it may try to process a workflow for an entire collection.

Related: It would be good to have a way to purge the spot queue in these cases. Right now my workaround is to delete the compute environment and redeploy.

**Comment by jkeifer** [comment]
This issue is de facto closed by #78, as we have removed feed-stac-api. However, this issue is good feedback if and when we decide to package that feeder in a resource plugin.
