### ISSUE TITLE
Better separation of cli/deploy code from tasks/feeders

### ISSUE THREAD

**Issue by matthewhanson** [cirrus-geo/cirrus-geo#53]
I'm not fond of the all the modules falling under a cirrus/cli package, since there's a difference between task code that may be used by the CLI (which may be used without the CLI) and code that is the actual CLI.  I'd like to see a better separation of packages here. 

For instance, we roughly have something like:
- cirrus-deploy: code that uses other code and templates to create a CF template
- cirrus-cli: the actual CLI code that calls cirrus-deploy functions
- cirrus-components: this is already a logical grouping, except it's under cli when they aren't really CLI specific.

These are just initial thoughts, we can talk through.

**Comment by trevorskaggs** [comment]
👍  to `cirrus-components` recommendation.
