### ISSUE TITLE
support task repositories

### ISSUE THREAD

**Issue by matthewhanson** [cirrus-geo/cirrus-geo#56]
Core tasks are included in this Cirrus package (e.g., `publish`), as they are included in every deployment. However, tasks that are included in individual workflows (e.g., `convert-to-cog`) it often makes sense to version individually, and thus, also code version individually.

This is nearly always the case with batch tasks. A batch task repo would exist that is expected to publish a compatible docker image.  However, with tasks that are written as Lambda functions (which can be used in batch with the [cirrus-task-lambda-as-batch](https://github.com/cirrus-geo/cirrus-task-lambda-as-batch) task), they would be included in the client-side repo for the cirrus deployment.

There should be a documented way to define tasks by linking to task repos. What would the task repos need to contain?

**Comment by jkeifer** [comment]
This is addressed by component plugins and/or lambda image support. See #139  and #104.
