### ISSUE TITLE
Add in STAC processing extension support to tasks

### ISSUE THREAD

**Issue by matthewhanson** [cirrus-geo/cirrus-geo#57]
The [STAC processing](https://github.com/stac-extensions/processing) extension provides a way to specify software versions (via `processing:software` field). 

A task can be considered a single unit of processing software, and therefore each task should update all output STAC Items it modifies/creates with it's name and version.

**Comment by jkeifer** [comment]
OBE as handled by https://github.com/stac-utils/stac-task.
