### ISSUE TITLE
Review config for update-state

### ISSUE THREAD

**Issue by matthewhanson** [cirrus-geo/cirrus-geo#80]
Need to review implicit queue config for the update-state lambda

**Comment by jkeifer** [comment]
I looked into this a bit and found the following:

* How to specify a DLQ is unclear with the old version of serverless we are using
* EventBridge by default will retry events 185 times (for retriable errors) and will keep events for 24 hours
* It is unclear to me how frequently it will retry through those 185 attempts
* If we do miss an event for some reason, the result will be a hanging cirrus job (stuck in `PROCESSING`)

It seems that a prerequisite for specifying a DLQ is upgrading our version of serverless (or replacing serverless). That or we could convert the events on the `update-state` function to be pure cloudformation, and not use the serverless event templating. If we were to do the latter, it points to a need to allow arbitrary cloudformation resources on lambda definitions, similar to how we support cloudformation on batch tasks.

While I believe we need to upgrade and/or replace serverless, and I think lambda cloudformation support makes sense, given the effort involved with the above relative to the need with regard to `update-state`, I have to question if we really need to be concerned about an issue here. That is, the worst case here is a job stuck in `PROCESSING`, which we could rather trivially detect by comparing jobs in `PROCESSING` for a long duration with the step function execution state. Adding a DLQ only makes us aware of this condition by the presence of a message in that DLQ _assuming the DLQ actually works_, which if the lambda doesn't I'm not sure if it is a given that the DLQ would.

I would therefore suggest we not worry about the configuration here. The defaults seem sufficient for >=99.99% of executions. I would recommend, if we were to do anything, to add some way to verify jobs in `PROCESSING` against their executions as an out-of-band way of detecting problems.

@matthewhanson how do you feel about closing this issue without any further action?

**Comment by jkeifer** [comment]
Closing this out for now as we are okay with the current behavior. If we have issues in the future we will create a new issue to address them.
